### ISSUE TITLE
How can I switch the kernel of firmware from 5.10.* to 5.15.*?

### ISSUE THREAD

**Issue by BioXeon** [astolfogit/miwifi-r3-production#11]
Halo, I made a fork from your repository and have the same mi router 3. I configured mesh option and if I use firmware with 5.15.* kernel , I hadn't any problems with it. But if I use firmware with 5.10.* kernel, which is the main one today, I had some problems with it and some others. 
How can I switch the kernel of firmware from 5.10.* to 5.15.* in my config file and so on? So that I can build my next firmwares including the kernel 5.15.*  
TY for your time.

**Comment by astolfogit** [comment]
Hello there. The maintainer of the x-wrt repo usually knows better which kernel version to use (referring to this commit https://github.com/x-wrt/x-wrt/commit/cdd527ae3fe6deea4573f8bfb0ccd32807802347)
In theory you could try changing KERNEL_PATCHVER from 5.10 to 5.15 in target/linux/ramips/mt7620/target.mk, but i cannot guarantee you that it will compile and work just fine

Moreover, i haven't owned miwifi r3 for over a year now and i have no idea how openwrt's doing in 2023 :(

**Comment by BioXeon** [comment]
I see. What did you choose as a replacement?

**Comment by astolfogit** [comment]
At the moment using mi 4a gigabit at one place and mi 3g (old ver.) at the other
