### ISSUE TITLE
opkg_download: Failed to download wget returned 8.

### ISSUE THREAD

**Issue by Spp595** [astolfogit/miwifi-r3-production#14]
Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/x/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/x/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/x/Packages.gz, wget returned 8.

**Comment by vulpeace** [comment]
Please refer to the older issue (https://github.com/astolfogit/miwifi-r3-production/issues/4)
You should use google translate
