### ISSUE TITLE
Cannot install openconnect client

### ISSUE THREAD

**Issue by slydiman** [astolfogit/miwifi-r3-production#17]
Cannot install openconnect client because kmod-tun is incompatible. The error message is following
```
The installed version of package kernel is not compatible, 
require 5.15.148-1-788d7be9… 
while 5.15.148-1-71a8d514… is installed.
```
Hope you can fix this problem. 
Thanks

**Comment by vulpeace** [comment]
It's not a problem. Please refer to the previous issues regarding this behaviour.
