### ISSUE TITLE
Router reboots under load | Роутер перезагружается при нагрузке 

### ISSUE THREAD

**Issue by SwifterGrip** [astolfogit/miwifi-r3-production#18]
English:
Router reboots under heavy load (e.g. 2 2k youtube videos in different tabs at the same time)
I tried to install release, and compiled by myself versions.

When I put openwrt build version “NitroOxid 1.0.8 8 r6817-bd8abfe344 / LuCI Master (git-18.153.65511-660e4f5)” (it's about 2019, taken from 4pda), then no reboots happen
Also no reboots on the previous OpenWRT firmware (can't find it anymore today)

If you have any older versions of xwrt for this router, I'd like to check how they work on it, as it takes me about 5 hours to compile them

#####################################################################

Russian:
Роутер перезагружается при сильной нагрузке (например 2 2к youtube видео в разных вкладках одновременно)
Пытался устанавливать release, и скомпилированные самим мной версии

Когда я ставлю сборку openwrt версии "NitroOxid 1.0.8 8 r6817-bd8abfe344 / LuCI Master (git-18.153.65511-660e4f5)" (она примерно 2019 года, взята с 4pda), то никаких перезагрузок не происходит
Также никаких перезагрузок не было на предыдущей прошивке OpenWRT (сегодня уже не могу ее найти)

Если у вас есть какие нибудь старые версии xwrt под этот роутер, то я хотел бы проверить как они на нем работают, так как они компилируются у меня примерно 5 часов

**Comment by vulpeace** [comment]
https://github.com/x-wrt/build-release/releases - здесь официальные билды x-wrt, можете выбрать ramips-mt7620 и поставить соответствующий пакет. К сожалению (или к счастью) у меня этого роутера больше нет, я ничего проверить не могу, все баги на совести китайца-мейнтейнера проекта x-wrt.

**Comment by SwifterGrip** [comment]
Проблема решена!!!

Посмотрите что пишет основатель x-wrt про эту проблему на Xiaomi Router R3:
https://github.com/x-wrt/build-release/issues/38

Вот issue об этом на который он отсылает:
https://github.com/x-wrt/build-release/issues/37

Последняя стабильная версия для Xiaomi Router R3 по словам основателя:
https://github.com/x-wrt/build-release/releases/tag/v23.10_b202312150123

Этот архив распаковать - (x-wrt-23.10_b202312150123-ramips-mt7620.zip) и там будет sysupgrade образ для Xiaomi Router R3 (x-wrt-23.10-b202312150123-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.bin) который надо установить через luci
