### ISSUE TITLE
Opkg update: wget returned 8

### ISSUE THREAD

**Issue by kohawk** [astolfogit/miwifi-r3-production#4]
Пытался установить пакеты, при этом обновить репозитории, но как и на прошлой версии прошивки и на этой все ломается и пишет: wget returned 8.

Сайт сам с packages.gz выводит 404, https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/x/Packages.gz

Any idea how to fix that?

Вывод из консоли прилагаю: https://pastebin.com/vz4E0Zi5

P.S извиняюсь, если я осел и это давно решили, просто не могу ниче найти

**Comment by astolfogit** [comment]
Это я забыл один пакет, сейчас добавлю в конфиг и поставлю на сборку.

**Comment by astolfogit** [comment]
Все пакеты на месте, просто надо отредактировать конфиг /etc/opkg/distfeeds.conf

**Comment by astolfogit** [comment]
Да, просто таких расположений, куда указывают ссылки из конфига x-wrt, не существует на сервере openwrt. https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/ и дальше смотреть

**Comment by lavrenkov-sketch** [comment]
@astolfogit @kohawk какое в итоге решение ? можно пример рабочего `/etc/opkg/distfeeds.conf`

**Comment by astolfogit** [comment]
Нужно заменить в этом файле во всех ссылках x на валидную директорию, вроде 
> mipsel_24kc/x/Packages.gz => mipsel_24kc/packages/Packages.gz
Я так понимаю, это было сделано уважаемым ptpt52 специально, чтобы исключить возможные проблемы с несовместимостью пакетов и т.п.
