### ISSUE TITLE
Unable to install KMOD-USB-STORAGE failing with The installed version of package kernel is not compatible, require 5.10.131-1-df52e9f1… while 5.10.131-1-dcae98e3… is installed.

### ISSUE THREAD

**Issue by sahilkaul1** [astolfogit/miwifi-r3-production#7]
I have upgraded from existing version to https://github.com/astolfogit/miwifi-r3-production/releases/download/2022.07.23-0139/openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.bin

updated installed packages and not able to install KMOD-USB-STORAGE and its failing with the mentioned error

**Comment by astolfogit** [comment]
It's actually easier to just rebuild the binaries with all the packages you need included than trying to install the packages. Check this out - https://openwrt.org/faq/cannot_satisfy_dependencies

**Comment by astolfogit** [comment]
[openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip](https://github.com/astolfogit/miwifi-r3-production/files/9202629/openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip)
Try this out (change the extension from .zip to .bin). I've included KMOD-USB-STORAGE in the config file.

**Comment by tmuehlhoff** [comment]
> It's actually easier to just rebuild the binaries with all the packages you need included than trying to install the packages. Check this out - https://openwrt.org/faq/cannot_satisfy_dependencies

not if you're abroad with no data plan ;)

**Comment by sahilkaul1** [comment]
> [openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip](https://github.com/astolfogit/miwifi-r3-production/files/9202629/openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip) Try this out (change the extension from .zip to .bin). I've included KMOD-USB-STORAGE in the config file.

I tried this. Now i have KMOD-USB- STORAGE and KMOD-USB-STORAGE-UAS already installed but then i dont still have KMOD-USB-EXTRAS and NTFS-3G, FDISK available and they also have dependency on kernel version name. Would you kindly rebuild with expected kernel version name by these pkgs since i have never had such issues in earlier versions.

**Comment by astolfogit** [comment]
[openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip](https://github.com/astolfogit/miwifi-r3-production/files/9208858/openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip)
Fdisk isn't included, but it can be installed manually just fine since it doesn't depend on any kernel modules.

**Comment by sahilkaul1** [comment]
> [openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip](https://github.com/astolfogit/miwifi-r3-production/files/9208858/openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip) Fdisk isn't included, but it can be installed manually just fine since it doesn't depend on any kernel modules.

Hei Thank you mate, I tried this version also and made some progress in configuring File Sharing on openwrt server with Samba 4 and again hit a problem, I can not see my 64 GB pendrive in Mount Points see screenshot

![image](https://user-images.githubusercontent.com/110116527/181679592-586209cc-6bad-42e9-a750-115b4f45f16d.png)

where as I can see it when I do LSUSB 

![image](https://user-images.githubusercontent.com/110116527/181679941-0b2b1ca9-c4ce-4c1c-83bb-a1ad4e7d7341.png)

Not sure if it could be because I don't have packages and I cant directly install due to kernel dependency
kmod-fs-ext4
kmod-fs-vfat
kmod-fs-ntfs
e2fsprogs

Sorry to keep bothering but would you please point me to some step by step instruction on how to get rid of these kernel dependencies just like you are installing packages in the BIN file

**Comment by astolfogit** [comment]
You can't just get rid of these kernel dependencies, you have to satisfy them. With kernel modules, it comes down to recompiling the whole thing (https://github.com/x-wrt/x-wrt#quickstart - there's the instruction to building openwrt). It could've been easier with snapshot images, but i have no idea if x-wrt snapshots use the same kernel configuration as openwrt snapshots do, and if it's not the same, kernel hash sums won't match, resulting in "kernel is not compatible ...".

**Comment by astolfogit** [comment]
[Uploading openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip…]()
This one includes those three kernel modules. You can install e2fsprogs yourself.

**Comment by sahilkaul1** [comment]
> Uploading openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip… This one includes those three kernel modules. You can install e2fsprogs yourself.

Let me give it a try brother. I am probably not as good as you in Linux / OpenWRT why did this kernel dependency was not there in existing versions.

**Comment by astolfogit** [comment]
This one includes those three kernel modules. You can install e2fsprogs yourself.
https://drive.google.com/file/d/1yw7V8fY2gSz1FpDLnJnKVAKEhMmdkMe5/view?usp=sharing (github had some problems with uploading this file, idk why)

**Comment by sahilkaul1** [comment]
Closing this issue as have been able to mitigate this issue with last bin file provided.

**Comment by astolfogit** [comment]
I've tested an NTFS-formatted drive and an exFAT-formatted drive - both of them work fine.  I've updated the config file and launched the building workflow manually, new release will appear in a couple of hours.

**Comment by sahilkaul1** [comment]
> I've tested an NTFS-formatted drive and an exFAT-formatted drive - both of them work fine. I've updated the config file and launched the building workflow manually, new release will appear in a couple of hours. I hope this will actually resolve the issue.

Thanks friend. Do you mean going forward all releases will have these installed already or is it only this release. Because I downloaded the recent release of 30 July and it did not have these packages already installed.

**Comment by astolfogit** [comment]
These packages will be included in all future releases.
