### ISSUE TITLE
OpenVPN install

### ISSUE THREAD

**Issue by lavrenkov-sketch** [astolfogit/miwifi-r3-production#8]
I got error when trying install openvpn
```

root@local:~# opkg install luci-app-openvpn openvpn-openssl

Installing luci-app-openvpn (git-22.078.84282-64b80b8) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/luci-app-openvpn_git-22.078.84282-64b80b8_all.ipk
Installing luci-compat (git-22.215.25738-a70c570) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/luci-compat_git-22.215.25738-a70c570_all.ipk
Installing openvpn-openssl (2.5.7-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/openvpn-openssl_2.5.7-1_mipsel_24kc.ipk
Configuring luci-compat.
Configuring luci-app-openvpn.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.136-1-49283af6812d0dfa501ad31bb9153c3c) for kmod-tun
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-tun found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for openvpn-openssl:
 * 	kernel (= 5.10.136-1-49283af6812d0dfa501ad31bb9153c3c)
 * opkg_install_cmd: Cannot install package openvpn-openssl.
```

**Comment by astolfogit** [comment]
Please refer to [this ](https://github.com/astolfogit/miwifi-r3-production/issues/7)issue
> It's actually easier to just rebuild the binaries with all the packages you need included than trying to install the packages. Check this out - https://openwrt.org/faq/cannot_satisfy_dependencies

**Comment by vhick** [comment]
Possible Sir to have built-in sqm in your firmware? I don't know how to build and I don't have build environment.

I hope it will grant my request. Thank you very much.

**Comment by astolfogit** [comment]
[openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip](https://github.com/astolfogit/miwifi-r3-production/files/10475049/openwrt-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade.zip)
Try this out, should be working ig. I switched my router, cannot test builds for mi r3 myself anymore.

**Comment by vhick** [comment]
Thank you so much, Sir for continue supporting our router. I appreciate it!

I will try your attached build and give you feedback later.

Is it possible to build all the packages co-existing with your weekly firmware builds so we can upload them manually in luci? Is it possible to your build-script?

Thank you so much 👍

**Comment by vhick** [comment]
> sed -i 's/-hidden//g' /usr/share/luci/menu.d/*.json

This one works. And thank you for acknowledging my idea.

Thank you Dev! :)
